### ISSUE TITLE
Error when trying to create ticket

### ISSUE THREAD

**Issue by TheJoshue** [Sayrix/Ticket-Bot#454]
I setup the bot with docker compose and both services (the bot and postgres) synced correctly, works, however creating ticket always creates ticket-0 and when "bot is thinking" it's never ending, it gets stuck in that state when i create new channel; whenever i create new ticket it again says ticket-0...

```
TypeError [InvalidType]: Supplied parameter is not a User nor a Role.
    at PermissionOverwriteManager.upsert (/app/node_modules/discord.js/src/managers/PermissionOverwriteManager.js:101:30)
    at PermissionOverwriteManager.edit (/app/node_modules/discord.js/src/managers/PermissionOverwriteManager.js:150:17)
    at /app/dist/utils/createTicket.js:79:52
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'InvalidType'
} Promise {
  <rejected> TypeError [InvalidType]: Supplied parameter is not a User nor a Role.
      at PermissionOverwriteManager.upsert (/app/node_modules/discord.js/src/managers/PermissionOverwriteManager.js:101:30)
      at PermissionOverwriteManager.edit (/app/node_modules/discord.js/src/managers/PermissionOverwriteManager.js:150:17)
      at /app/dist/utils/createTicket.js:79:52
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    code: 'InvalidType'
  }
} undefined
```

**Comment by Sayrix** [comment]
That is not a bug, that's a config issue.

**Comment by TheJoshue** [comment]
> That is not a bug, that's a config issue.

Can you tell me what i did wrong?
```yml
{
	"clientId": "<ID>", // The id of the discord bot
	"guildId": "<ID>", // The id of the discord server
	"mainColor": "#f6c42f", // The hex color of the embeds by default
	"lang": "main", // If you want to set english please set "main"

	"openTicketChannelId": "830246874748682290", // The id of the channel where the message to create a ticket will be sent

	"ticketTypes": [
		// You have a limit of 25 types (the limit of Discord)
		{
			"codeName": "category-one", // The name need to be in lowercase
			"name": "Category One", // The name that will be displayed in the ticket
			"description": "Description of Category One", // The description of the Ticket in Create Ticket Menu
			"emoji": "💡", // The emoji of the type (can be blank)
			"color": "", // Can be a hex color or blank to use the main color
			"categoryId": "1170018943428218920", // The category id where the tickets will be created
			"ticketNameOption": "💡ticket-TICKETCOUNT", // Here is all parameter: USERNAME, USERID, TICKETCOUNT (set to blank to use the default name)
			"customDescription": "", // The custom description of the ticket type, here is all parameter: USERNAME, USERID, TICKETCOUNT, REASON1, 2, ect (set to blank to use the default description)
			"cantAccess": ["1111111111111111111"], // The roles who can't access to this ticket type
			"askQuestions": false, // If the bot should ask the reason of the ticket
			"questions": [], // Leave blank if you don't want to ask questions
			"staffRoles": ["829305198006501396"] // Category specific staff role (instead of the default ones)
		},
		{
			"codeName": "category-two", // The name need to be in lowercase
			"name": "Category Two", // The name that will be displayed in the ticket
			"description": "Description of Category Two", // The description of the Ticket in Create Ticket Menu
			"emoji": "🛑", // The emoji of the type (can be blank)
			"color": "#f8312f", // Can be a hex color or blank to use the main color
			"categoryId": "1170018943428218920", // The category id where the tickets will be created
			"ticketNameOption": "", // Here is all parameter: USERNAME, USERID, TICKETCOUNT (set to blank to use the default name)
			"customDescription": "Please explain your report in detail. If you have any images, please attach them to your message.", // The custom description of the ticket type, here is all parameter: USERNAME, USERID, TICKETCOUNT, REASON1, 2, ect (set to blank to use the default description)
			"cantAccess": ["2222222222222222222"], // The roles who can't access to this ticket type
			"askQuestions": false, // If the bot should ask the reason of the ticket
			"questions": [], // Leave blank if you don't want to ask questions
			"staffRoles": ["829305198006501396"] // Category specific staff role (instead of the default ones)
		},
		{
			"codeName": "other", // The name need to be in lowercase
			"name": "Other", // The name that will be displayed in the ticket
			"description": "Description of Category Other", // The description of the Ticket in Create Ticket Menu
			"emoji": "", // The emoji of the type (can be blank)
			"color": "", // Can be a hex color or blank to use the main color
			"categoryId": "1170018943428218920", // The category id where the tickets will be created
			"ticketNameOption": "", // Here is all parameter: USERNAME, USERID, TICKETCOUNT (set to blank to use the default name)
			"customDescription": "Thank you for your ticket, a staff will reply you as soon as possible\n\n__**What is the reason of the ticket?**__: REASON1", // The custom description of the ticket type, here is all parameter: USERNAME, USERID, TICKETCOUNT, REASON1, 2, ect (set to blank to use the default description)
			"cantAccess": [], // The roles who can't access to this ticket type
			"askQuestions": true, // If the bot should ask the reason of the ticket
			"staffRoles": ["829305198006501396"], // Category specific staff role (instead of the default ones)
			"questions": [
				// Maximum of 5 questions can be set due to discord's limit
				{
					"label": "What is the reason of the ticket?",
					"placeholder": "Please enter the reason",
					"style": "PARAGRAPH", // SHORT or PARAGRAPH
					"maxLength": 1000
				}
			]
		}
	],
	"ticketNameOption": "Ticket-USERNAME", // Here is all parameter: USERNAME, USERID, TICKETCOUNT

	// Ticket Claim Options
	"claimOption": {
		"claimButton": true, // Whether to enable ticket claim button or not
		// The X can be replaced with S (The staff that claimed the ticket) or U (The user that created the ticket)
		"nameWhenClaimed": "✔️ Ticket-TICKETCOUNT", // Here is all parameter: X_USERNAME, X_USERID, TICKETCOUNT
		"categoryWhenClaimed": "" // The category the ticket is moved to when claimed
	},

	"rolesWhoHaveAccessToTheTickets": ["521453395597459456", "2222222222222222222"], // Roles who can access to the tickets (Like the staff)/ Treat this as global admin role type of thing.

	"rolesWhoCanNotCreateTickets": [], // Roles who can	not create a tickets (Like a blacklist)

	"pingRoleWhenOpened": true,
	"roleToPingWhenOpenedId": ["829305198006501396"], // The role to ping when a ticket is opened

	"logs": true,
	"logsChannelId": "1315761131863675060", // The id of the channel where the logs will be sent
	
	"closeOption": {
		"closeButton": true, // If false the ticket can be closed only by doing /closes
		"dmUser": true, // Whether to DM the user when the ticket is closed
		"createTranscript": true, // If set to true, when the ticket is closed a transcript will be generated and sent in the logs channel
		"askReason": true, // If false the ticket will be closed without asking the reason
		"whoCanCloseTicket": "STAFFONLY", // STAFFONLY (roles configured at "rolesWhoHaveAccessToTheTickets") or EVERYONE
		"deleteTicket": false, // when enabled, it will delete the ticket on clicking close button
		"closeTicketCategoryId": "" // The id of the category where a closed ticket will be moved to. Leave blank to disable this feature
	},
	"uuidType": "uuid", // uuid or emoji

	"status": {
		"enabled": true, // If you want to enable the status of the bot
		"text": "Testing", // The text of the status
		"type": "CUSTOM", // PLAYING, WATCHING, LISTENING, STREAMING, COMPETING
		"url": "", // The url of the status if the type is STREAMING (can be blank)
		"status": "online" // online, idle, dnd, invisible set to online if the type is STREAMING
	},

	"maxTicketOpened": 0, // The number of tickets the user can open while another one is already open. Set to 0 to unlimited
	/*
	Whether or not to minimizing the tracking data that are being sent
	Enabling this will cause the telemetry to only send the software version and node version
	*/
	"minimalTracking": false,
	// Hide internal websocket logs
	"showWSLog": false
}

```
